version: '3.9'

networks:
  dev_network:

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M